server:
  port: 8888

spring:
  profiles:
    active: native

  application:
    name: config-server

# cloud related configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anandmohansinha/spring-cloud-config-repo
          default-label: main
          clone-on-start: true
        native:
          search-locations: classpath:/configurations
